# Matrix Rank

* Terminology: r or rank(A), non negative integer.
* Maximum possible ran is min(m,n)
* Rank is a property of the matrix, not columns or rows
* More terminology: full rank, full column-rank, full row-rank, singular
* Rank is the number of dimensions of information
* The rank is the number of columns that form a linearly independent set
* The maximum rank of a matrix is the smaller of mxn

In [1]:
import numpy as np

In [2]:
#FOR COLUMNS

#make a matrix
m = 4
n = 6

#Create a random matrix
A = np.random.randn(m,n)
print(A)

#What is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print(f'Matrix Rank of A is: {str(ra)}')

#set last column to be repeat of penultimate column
B = A
B[:,-1] = B[:,-2]
print(B)

rb = np.linalg.matrix_rank(B)
print(f'rank = {str(rb)}')


[[-0.29394854 -0.78140199 -0.3633244  -1.59068879  1.36733143  1.09856826]
 [ 0.37420836  0.0166773  -1.24357443  1.17532332 -0.39557632 -0.19936619]
 [-0.97738937  0.56809948  0.34032031  0.24426142 -0.3166968   0.07578634]
 [-0.99324723  0.67248198  0.23172864  0.71572762 -0.38564842 -0.70743656]]
Matrix Rank of A is: 4
[[-0.29394854 -0.78140199 -0.3633244  -1.59068879  1.36733143  1.36733143]
 [ 0.37420836  0.0166773  -1.24357443  1.17532332 -0.39557632 -0.39557632]
 [-0.97738937  0.56809948  0.34032031  0.24426142 -0.3166968  -0.3166968 ]
 [-0.99324723  0.67248198  0.23172864  0.71572762 -0.38564842 -0.38564842]]
rank = 4


In [3]:
#FOR ROWS

#make a matrix
m = 4
n = 6

#Create a random matrix
A = np.random.randn(m,n)
print(A)

#What is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print(f'Matrix Rank of A is: {str(ra)}')

#set last column to be repeat of penultimate row
B = A
B[-1,:] = B[-2,:]
print(B)

rb = np.linalg.matrix_rank(B)
print(f'rank = {str(rb)}')

[[-0.04384453  1.51289172 -0.57433914 -0.25441648 -0.69339238 -1.2479896 ]
 [ 0.0867115   0.60379491  0.96268531 -1.20001524 -0.51887082 -1.66822505]
 [-0.00940717  0.46041954 -0.42754436  0.65748101  0.58773581 -1.55090969]
 [ 0.76610472 -1.14213615 -1.74477869  0.02479109  0.55316336 -0.72577724]]
Matrix Rank of A is: 4
[[-0.04384453  1.51289172 -0.57433914 -0.25441648 -0.69339238 -1.2479896 ]
 [ 0.0867115   0.60379491  0.96268531 -1.20001524 -0.51887082 -1.66822505]
 [-0.00940717  0.46041954 -0.42754436  0.65748101  0.58773581 -1.55090969]
 [-0.00940717  0.46041954 -0.42754436  0.65748101  0.58773581 -1.55090969]]
rank = 3


In [4]:
#adding noise to a rank-deficient matrix

#square for convenience
A = np.round(10*np.random.randn(m,m))
print(f'A :\n {A}')

#reduce the rank
A[:,-1] = A[:,-2]
print(f'A with the last 2 columns equal:\n {A}')

#noise level
noiseamp = 0.01

#add the noise
B = A + noiseamp*np.random.randn(m,m)

print(f'Rank with no noise: \n{str(np.linalg.matrix_rank(A))}')
print(f'Rank with noise: \n{str(np.linalg.matrix_rank(B))}')

A :
 [[ 11.   1.  -5. -23.]
 [ -4.   8.  20.  -1.]
 [  1.  16.   0. -13.]
 [  1.   3.  -3.  -8.]]
A with the last 2 columns equal:
 [[11.  1. -5. -5.]
 [-4.  8. 20. 20.]
 [ 1. 16.  0.  0.]
 [ 1.  3. -3. -3.]]
Rank with no noise: 
3
Rank with noise: 
4


$$ rank(A+B) \leq rank(A) + rank(B) $$
$$\text{rank}(A+B) \leq \min\{\text{rank}(A), \text{rank}(B)\}$$


Consider the following matrices, all 10x10, and their ranks:

A: r=3;  B: r=2;  C: r=1;  D: r=6

If these matrices contained randomly generated numbers, what is the maximum possible rank of the matrix product (A+B)(C+D)?
The maximum possible rank of (C+D) is 7. The maximum possible rank of (A+B) is 5. And the maximum possible rank of multiplied matrices is the smaller of their two ranks, which is 5. We assume that matrices of randomly generated numbers have maximum possible rank

## Challenge

In [5]:
#create reduced-rank matrices using matrix multiplication

#create a 10x10 matrix with rank 4 (use matrix multiplication)

A = np.random.randn(10,4)
B = np.random.randn(4,10)
C = A@B
print(f'A :\n {A}')

print(f'B :\n {B}')

print(f'C :\n {C}')
print(f'Shape of C :{np.shape(C)}')
rc = np.linalg.matrix_rank(C)
print(f'Matrix Rank of C :{rc}'), print(' ')


#generalize the produce to create any MxN matrix with rank r
m = 8
n = 47
r = 3

A = np.random.randn(m,r) @ np.random.randn(r,n) #min of (8x3)(3x47) = 3
print(f'Shape of A :{np.shape(A)}')
ra = np.linalg.matrix_rank(A)
print(f'Matrix Rank of A :{ra}')

A :
 [[ 0.35857868 -0.4064164   0.55663009 -1.76393676]
 [-1.31067166  0.60435204 -0.81840196  0.20822253]
 [ 3.33844412 -0.86137752  0.5584113  -1.70626821]
 [ 0.64428386 -0.56346309 -0.35451296 -0.72852471]
 [ 0.45855157 -0.03608371  1.30675717  1.14824522]
 [ 1.10380895  0.12005651 -0.14546178  0.58950434]
 [ 0.50339819 -1.17754946  0.54263653  0.66931225]
 [ 0.63994015  0.56702044  1.44976808  0.81030972]
 [-2.05919258  2.82027049  0.90435868  1.08091621]
 [-0.05196258  0.37716285  0.04334915  0.48679395]]
B :
 [[-0.49517389  0.39431972 -0.12753002  1.7161536   0.15415628  1.14823498
   0.44795149  0.55108374  1.16349255 -0.69520185]
 [ 0.55930214  2.06466647 -1.75029168 -1.47052341  0.38324982 -0.13074972
  -1.20855141 -0.60474578  0.80062193 -0.66615888]
 [ 0.07815497  0.49063338  0.2737816  -0.27113746  0.87055479 -1.26038482
   1.07110835 -0.21921194  0.62238074 -0.79798177]
 [-0.96166529  1.88573884 -0.87646916 -1.1677083  -0.50138821 -1.87570781
  -1.37447135 -0.89000129  0.4

## Challenge

In [17]:
# test whether the matrix rank is invariant to scalar multiplication
    # rank(A) != rank(lambda.A)

#create two matrices: full rank and recuded rank(random)

F = np.random.randn(5,5)
R = np.random.randn(5,4)

rf = np.linalg.matrix_rank(F)
rr = np.linalg.matrix_rank(R)

#create the scalar :
lamb = 1.2234

FwS = np.multiply(F,lamb)
RwS = np.multiply(R,lamb)

rFwS = np.linalg.matrix_rank(FwS)
rRwS = np.linalg.matrix_rank(RwS)

# Print ranks of F, R, l*F, l* R
print(f'Rank of Full: {rf}')
print(f'Rank of Reduced: {rr}')
print(f'Rank of Full with scalar: {rFwS}')
print(f'Rank of Reduced with scalar: {rRwS}')

#check wether rank (l*F) ==l*rank(F)

rank_l_F = rFwS
print(rank_l_F)
l_rank_F = lamb*rf
print(l_rank_F)
if rank_l_F != l_rank_F:
    print("Ok, Computer! They are different")
else:
    print("Equals")

Rank of Full: 5
Rank of Reduced: 4
Rank of Full with scalar: 5
Rank of Reduced with scalar: 4
5
6.117
Ok, Computer! They are different


# Rank of AtA and AAt

## $$ rank(A) = rank(A^TA)= rank(A)= rank(AA^T)$$

## Challenge

In [29]:
#rules: rank of AB <=min(rank(A), rank(B))
    #rank of A+B <=rank(A) + rank(B)

#generate two matrices (A and B), 2x5
m = 2
n = 5

A = np.random.randn(m,n)
B = np.random.randn(m,n)

ra = np.linalg.matrix_rank(A)
rb = np.linalg.matrix_rank(B)
print(f'Rank of A: {ra}')
print(f'Rank of B: {rb}')

#compute Ata and BtB
AtA = A.T@A
BtB = B.T@B

print(f'AtA: {AtA}')
print(f'BtB: {BtB}')

#find ranks of AtA and BtB
rAtA = np.linalg.matrix_rank(AtA)
rBtB = np.linalg.matrix_rank(BtB)

print(f'Rank of Ata: {rAtA}')
print(f'Rank of Btb: {rBtB}')

sum_rank = np.linalg.matrix_rank(AtA+BtB)
mult_rank = np.linalg.matrix_rank(AtA@BtB)

print(f'Rank of Sum: {sum_rank}') # should be 4, not 2
print(f'Rank of Multiplication: {mult_rank}')

Rank of A: 2
Rank of B: 2
AtA: [[ 3.07289129  0.15876883  1.44968017  2.73324124 -1.34721869]
 [ 0.15876883  0.02124973  0.09947226  0.23959583 -0.05128049]
 [ 1.44968017  0.09947226  0.73018196  1.4747188  -0.6010539 ]
 [ 2.73324124  0.23959583  1.4747188   3.17292517 -1.06011629]
 [-1.34721869 -0.05128049 -0.6010539  -1.06011629  0.61639312]]
BtB: [[ 1.08247715 -0.05577557  1.50276471  0.58583801 -1.66797041]
 [-0.05577557  0.17766291 -0.46637372  0.20447951  0.72210458]
 [ 1.50276471 -0.46637372  2.95171416  0.29111832 -3.7311767 ]
 [ 0.58583801  0.20447951  0.29111832  0.6321093  -0.04862142]
 [-1.66797041  0.72210458 -3.7311767  -0.04862142  4.88551406]]
Rank of Ata: 2
Rank of Btb: 2
Rank of Sum: 4
Rank of Multiplication: 2


# Making a Matrix Full-Rank by shifting

## $$ Ã = A + \lambda I $$ 

In [37]:
# size of matrix
m = 30

#create the square symmetric matrix
A = np.random.randn(m,m)
#print(f'Matrix A: \n {A}')
A = np.round(10*A.T@A) 

#print(f'Matrix A: \n {A}')

#reduce the rank
A[:,0] = A[:,1] #reduces the rank to 29
print(f'Matrix A: \n {A}')

#shift the amount (l = lambda)
l = 0.01

#new matrix
B = A + l*np.eye(m,m)

#print information
print(f'rank(without shift) = {np.linalg.matrix_rank(A)}')
print(f'rank(with shift) = {np.linalg.matrix_rank(B)}')

Matrix A: 
 [[   1.    1.  105.    6.   -5.  -43.    7.  -27.   52. -152.  122.   87.
    61.   28.   64.   49.  -11.  -21. -118.  -62.   52.   89.   47.   23.
   -15.   52.   52.   36.   -3.  -62.]
 [ 199.  199.    3.  -36.  -23.   52.  -11.   -5.  -27.  -11.  -27.   35.
    17.   11.   28.   26.  -37.   13.   35.   19.  -23.   83.   22.  -63.
   -72.   29.  -20.   71.  -53.   37.]
 [   3.    3.  238.  -25.   36.  -93.  -84.  -17.   12. -106.   37.  -35.
   -36.  -30.  -74.   24.   35.  -71.   -7.  -74.  -21.   27.   56.  -19.
   -84.   -4.   58.   20.  -13.  -28.]
 [ -36.  -36.  -25.  169.   47.  -42.   15.  -22.   24.  -36.    9.  -77.
   -11.   43.  -27.  -43.   14.  -67.  -12.   58.  -28.  -46.  -34.  -11.
   -19.   18.  -28.  -23.    9.  -27.]
 [ -23.  -23.   36.   47.  191.  -75.  -25.  -33.  -42.   -1.  -14.    3.
    37.   18.   28.  -40.   21. -105.  -23.   65.   19.   52.  -19.  -11.
   -10.   39.   30.   15.   20.   33.]
 [  52.   52.  -93.  -42.  -75.  315.   39.   15.   2

## Challenge

In [46]:
# Determine wheter this vector
v = np.array([[1, 2, 3, 4]]).T
print(v)

#is in the span of these sets
S = np.vstack(([4, 3, 6, 2], [0,4,0,1])).T
T = np.vstack(([1, 2, 2, 2], [0,0,1,2])).T
print(S)
print(T)

Sv = np.concatenate((S,v),axis=1)
Tv = np.concatenate((T,v),axis=1)

print(Sv)
print(Tv)

print(' ')
print(np.linalg.matrix_rank(Sv))
print(np.linalg.matrix_rank(Tv))

[[1]
 [2]
 [3]
 [4]]
[[4 0]
 [3 4]
 [6 0]
 [2 1]]
[[1 0]
 [2 0]
 [2 1]
 [2 2]]
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]
 
3
2
